# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\"L\n\x16\x46\x61\x63\x65RecognitionRequest\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x10\n\x08img_orig\x18\x02 \x01(\x0c\x12\x0e\n\x06target\x18\x03 \x01(\t\"K\n\x15\x46\x61\x63\x65RecognitionReplay\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07img_out\x18\x02 \x01(\x0c\x12\x0f\n\x07success\x18\x03 \x01(\x08\"\x12\n\x10HeartBeatRequest\"\x11\n\x0fHeartBeatReplay2\x8d\x01\n\x0bTaskService\x12J\n\x15task_face_recognition\x12\x17.FaceRecognitionRequest\x1a\x16.FaceRecognitionReplay\"\x00\x12\x32\n\theartbeat\x12\x11.HeartBeatRequest\x1a\x10.HeartBeatReplay\"\x00\x62\x06proto3')



_FACERECOGNITIONREQUEST = DESCRIPTOR.message_types_by_name['FaceRecognitionRequest']
_FACERECOGNITIONREPLAY = DESCRIPTOR.message_types_by_name['FaceRecognitionReplay']
_HEARTBEATREQUEST = DESCRIPTOR.message_types_by_name['HeartBeatRequest']
_HEARTBEATREPLAY = DESCRIPTOR.message_types_by_name['HeartBeatReplay']
FaceRecognitionRequest = _reflection.GeneratedProtocolMessageType('FaceRecognitionRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONREQUEST,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognitionRequest)
  })
_sym_db.RegisterMessage(FaceRecognitionRequest)

FaceRecognitionReplay = _reflection.GeneratedProtocolMessageType('FaceRecognitionReplay', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONREPLAY,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:FaceRecognitionReplay)
  })
_sym_db.RegisterMessage(FaceRecognitionReplay)

HeartBeatRequest = _reflection.GeneratedProtocolMessageType('HeartBeatRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATREQUEST,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:HeartBeatRequest)
  })
_sym_db.RegisterMessage(HeartBeatRequest)

HeartBeatReplay = _reflection.GeneratedProtocolMessageType('HeartBeatReplay', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATREPLAY,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:HeartBeatReplay)
  })
_sym_db.RegisterMessage(HeartBeatReplay)

_TASKSERVICE = DESCRIPTOR.services_by_name['TaskService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FACERECOGNITIONREQUEST._serialized_start=14
  _FACERECOGNITIONREQUEST._serialized_end=90
  _FACERECOGNITIONREPLAY._serialized_start=92
  _FACERECOGNITIONREPLAY._serialized_end=167
  _HEARTBEATREQUEST._serialized_start=169
  _HEARTBEATREQUEST._serialized_end=187
  _HEARTBEATREPLAY._serialized_start=189
  _HEARTBEATREPLAY._serialized_end=206
  _TASKSERVICE._serialized_start=209
  _TASKSERVICE._serialized_end=350
# @@protoc_insertion_point(module_scope)
